export const blogPosts = [
  {
    id: 'b1',
    title: 'Best Hotels in Purnea Near Bus Stand | Hotel Guide 2026',
    excerpt: 'Looking for the best hotel in Purnea near Bus Stand? Compare deluxe AC rooms, budget stays, family rooms, and luxury options at Hotel Surya Bella Casa.',
    date: 'Mar 15, 2026',
    category: 'Hotel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3815.avif',
    link: '/blog/best-hotels-in-purnea-near-bus-stand',
  },
  {
    id: 'b2',
    title: 'Rooftop Restaurant in Purnea | Best Family Dining Near Bus Stand',
    excerpt: 'Discover the best rooftop restaurant in Purnea near Bus Stand. Multi cuisine dining at Hotel Surya Bella Casa — Indian, Tandoor, Mughlai, Asian & Continental.',
    date: 'Feb 20, 2026',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3739.avif',
    link: '/blog/rooftop-restaurant-in-purnea',
  },
  {
    id: 'b3',
    title: 'Banquet Hall & Wedding Venue in Purnea | Marriage Hall Near Bus Stand',
    excerpt: 'Plan your wedding at the best banquet hall in Purnea near Bus Stand. Wedding venue, marriage hall, conference hall for events and parties at Hotel Surya Bella Casa.',
    date: 'Jan 10, 2026',
    category: 'Events & Weddings',
    image: 'https://bookonelocal.in/cdn/IMG_3766.avif',
    link: '/blog/banquet-hall-wedding-venue-in-purnea',
  },
  {
    id: 'b4',
    title: 'Business Hotel in Purnea | Corporate Stay Near Bus Stand for Professionals',
    excerpt: 'Best business hotel in Purnea near Bus Stand with conference hall, meeting room, high-speed WiFi. Ideal for corporate travelers and office visitors.',
    date: 'Dec 5, 2025',
    category: 'Business Travel',
    image: 'https://bookonelocal.in/cdn/IMG_3703.avif',
    link: '/blog/business-hotel-in-purnea',
  },
  {
    id: 'b5',
    title: 'Family Hotel in Purnea | Safe Family Stay Near Bus Stand & Vikass Market',
    excerpt: 'Best family hotel in Purnea near Bus Stand and Vikass Market. Spacious family rooms, safe environment, elevator access, 24/7 staff assistance.',
    date: 'Nov 18, 2025',
    category: 'Family Stay',
    image: 'https://bookonelocal.in/cdn/IMG_3701.avif',
    link: '/blog/family-hotel-in-purnea',
  },
  {
    id: 'b6',
    title: 'Places to Visit in Purnea | Nearby Attractions & Things to Do Near Bus Stand',
    excerpt: 'Explore places to visit in Purnea near Hotel Surya Bella Casa. Maa Puran Devi Temple, Purnea Court, shopping markets, and local attractions near Bus Stand.',
    date: 'Oct 22, 2025',
    category: 'Travel Guide',
    image: '/purneacity.jpg',
    link: '/blog/places-to-visit-in-purnea',
  },
];
