export interface BlogPost {
  id: string
  title: string
  excerpt: string
  date: string
  dateISO: string
  dateModifiedISO: string
  category: string
  image: string
  link: string
  cluster: 'hotel' | 'restaurant' | 'banquet' | 'travel'
}

export const blogPosts: BlogPost[] = [
  // ── Cluster 1: Hotel ──────────────────────────────────────────
  {
    id: 'b1',
    title: 'Best Resorts Near Ajodhya Hill | Forest Stay Guide 2026',
    excerpt: 'Looking for the best resort near Ajodhya Hill? Compare forest cottages, luxury suites, and family rooms at The Divine Oasis, Purulia.',
    date: 'Mar 15, 2026',
    dateISO: '2026-03-15',
    dateModifiedISO: '2026-07-23',
    category: 'Resort Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064432393-WhatsApp Image 2026-05-11 at 15.42.15.jpg',
    link: '/blog/best-resorts-near-ajodhya-hill',
    cluster: 'hotel',
  },
  {
    id: 'b4',
    title: 'Corporate Offsite Resort in Purulia | Hilltop Team Retreat',
    excerpt: 'Best corporate offsite resort in Purulia. Forest cottages, seating areas, drinks & hors d’oeuvres, and great WiFi for team retreats above Ajodhya Hill.',
    date: 'Dec 5, 2025',
    dateISO: '2025-12-05',
    dateModifiedISO: '2026-07-23',
    category: 'Corporate Retreats',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064523804-WhatsApp Image 2026-05-11 at 15.42.14.jpg',
    link: '/blog/corporate-offsite-resort-in-purulia',
    cluster: 'hotel',
  },
  {
    id: 'b5',
    title: 'Family Resort in Ajodhya Hill | Kid-Friendly Forest Stay',
    excerpt: 'Best family resort in Ajodhya Hill. Spacious family rooms, safe forest setting, organic farm walks, and 24/7 staff assistance at The Divine Oasis, Purulia.',
    date: 'Nov 18, 2025',
    dateISO: '2025-11-18',
    dateModifiedISO: '2026-07-23',
    category: 'Family Stay',
    image: 'https://bookonelocal.in/cdn/2026-05-13-063550245-WhatsApp Image 2026-05-11 at 15.54.31 (1).jpg',
    link: '/blog/family-resort-in-ajodhya-hill',
    cluster: 'hotel',
  },
  {
    id: 'b7',
    title: 'Luxury Cottage Resort in Purulia | Premium Hilltop Stays',
    excerpt: 'Experience luxury at The Divine Oasis in Purulia. A premium Luxury Suite Cottage, forest views, and private cottages on Ajodhya Hill.',
    date: 'Jul 20, 2026',
    dateISO: '2026-07-20',
    dateModifiedISO: '2026-07-23',
    category: 'Luxury Stay',
    image: 'https://bookonelocal.in/cdn/2026-05-13-063018320-WhatsApp Image 2026-05-11 at 15.53.21.jpg',
    link: '/blog/luxury-cottage-resort-in-purulia',
    cluster: 'hotel',
  },
  {
    id: 'b8',
    title: 'Resorts Near Purulia Railway Station | Stay 42.6 km from Junction',
    excerpt: 'Finding resorts near Purulia Railway Station? The Divine Oasis is 42.6 km from Purulia Junction, a scenic drive into the Ajodhya Hills.',
    date: 'Jul 18, 2026',
    dateISO: '2026-07-18',
    dateModifiedISO: '2026-07-23',
    category: 'Resort Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064448375-WhatsApp Image 2026-05-11 at 15.42.13.jpg',
    link: '/blog/resorts-near-purulia-railway-station',
    cluster: 'hotel',
  },

  {
    id: 'b20',
    title: 'Best Cottages in Ajodhya Hill | Mud Cottages, Suites & Vista Pods',
    excerpt: 'Book the best cottages in Ajodhya Hill at The Divine Oasis. Premium Deluxe Mud Cottages, a Luxury Suite, VISTA Four Beds, and Vista Pod Cottages near the forest reserve.',
    date: 'Jul 23, 2026',
    dateISO: '2026-07-23',
    dateModifiedISO: '2026-07-23',
    category: 'Resort Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-063246599-WhatsApp Image 2026-05-11 at 15.52.07 (1).jpg',
    link: '/blog/best-cottages-in-ajodhya-hill',
    cluster: 'hotel',
  },

  // ── Cluster 2: Restaurant ─────────────────────────────────────
  {
    id: 'b2',
    title: 'Organic Farm Dining in Purulia | Farm-to-Table at Ajodhya',
    excerpt: 'Discover organic farm-to-table dining near Ajodhya Hill. Fresh produce, veg thali, and open-air meals at The Divine Oasis organic farm, Purulia.',
    date: 'Feb 20, 2026',
    dateISO: '2026-02-20',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064504242-WhatsApp Image 2026-05-11 at 15.42.12.jpg',
    link: '/blog/organic-farm-dining-in-purulia',
    cluster: 'restaurant',
  },
  {
    id: 'b9',
    title: 'Best Dining Near Ajodhya Hill | Top Rated Forest Restaurant',
    excerpt: 'Looking for the best dining near Ajodhya Hill? The Divine Oasis serves farm-fresh multi-cuisine food and barbeque evenings above Purulia.',
    date: 'Jul 15, 2026',
    dateISO: '2026-07-15',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064437235-WhatsApp Image 2026-05-11 at 15.42.11 (1).jpg',
    link: '/blog/best-dining-near-ajodhya-hill',
    cluster: 'restaurant',
  },
  {
    id: 'b10',
    title: 'Fine Dining in Purulia | Elegant Forest-Edge Experience',
    excerpt: 'Enjoy fine dining in Purulia at The Divine Oasis. Elegant ambiance, curated menu, hilltop views, and premium service near Ajodhya Hills.',
    date: 'Jul 12, 2026',
    dateISO: '2026-07-12',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064507861-WhatsApp Image 2026-05-11 at 15.42.13 (1).jpg',
    link: '/blog/fine-dining-in-purulia',
    cluster: 'restaurant',
  },
  {
    id: 'b11',
    title: 'Family Dining in Purulia | Kid-Friendly Meals Near Ajodhya',
    excerpt: 'Find family-friendly dining in Purulia. The Divine Oasis offers a pure veg thali, spacious seating, and calm forest views perfect for kids.',
    date: 'Jul 10, 2026',
    dateISO: '2026-07-10',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064452634-WhatsApp Image 2026-05-11 at 15.42.14 (2).jpg',
    link: '/blog/family-dining-in-purulia',
    cluster: 'restaurant',
  },
  {
    id: 'b12',
    title: 'Best Dinner Place in Purulia | Barbeque Evenings at Ajodhya',
    excerpt: 'Searching for the best dinner place in Purulia? Enjoy barbeque evenings and hilltop dinners under the stars at The Divine Oasis, Ajodhya.',
    date: 'Jul 8, 2026',
    dateISO: '2026-07-08',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064459381-WhatsApp Image 2026-05-11 at 15.42.11.jpg',
    link: '/blog/best-dinner-place-in-purulia',
    cluster: 'restaurant',
  },

  // ── Cluster 3: Banquet & Events ───────────────────────────────
  {
    id: 'b3',
    title: 'Wedding Venue in Purulia | Hilltop Celebrations Near Ajodhya',
    excerpt: 'Plan your wedding at the best outdoor venue in Purulia. Hilltop ceremonies, social events, and guest cottages at The Divine Oasis near Ajodhya Hills.',
    date: 'Jan 10, 2026',
    dateISO: '2026-01-10',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Weddings',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064516081-WhatsApp Image 2026-05-11 at 15.42.14 (1).jpg',
    link: '/blog/wedding-venue-in-purulia',
    cluster: 'banquet',
  },
  {
    id: 'b13',
    title: 'Outdoor Wedding Venue in Purulia | Forest & Hilltop Ceremonies',
    excerpt: 'Book the best outdoor wedding venue in Purulia at The Divine Oasis. Open-air hilltop ceremonies, catering, decor, and cottage blocks for guests near Ajodhya Hills.',
    date: 'Jul 5, 2026',
    dateISO: '2026-07-05',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Weddings',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064511341-WhatsApp Image 2026-05-11 at 15.42.13 (2).jpg',
    link: '/blog/outdoor-wedding-venue-in-purulia',
    cluster: 'banquet',
  },
  {
    id: 'b14',
    title: 'Birthday Party Resort in Purulia | Private Celebrations at Ajodhya',
    excerpt: 'Celebrate your birthday at The Divine Oasis in Purulia. Private party spaces, barbeque stand, and group cottage bookings on Ajodhya Hill.',
    date: 'Jul 3, 2026',
    dateISO: '2026-07-03',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Parties',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064455582-WhatsApp Image 2026-05-11 at 15.42.15 (1).jpg',
    link: '/blog/birthday-party-resort-in-purulia',
    cluster: 'banquet',
  },
  {
    id: 'b15',
    title: 'Corporate Event Venue in Purulia | Conference & Team Outings',
    excerpt: 'Host corporate events in Purulia at The Divine Oasis. Seating areas, WiFi, catering, and team outing packages above Ajodhya Hills.',
    date: 'Jul 1, 2026',
    dateISO: '2026-07-01',
    dateModifiedISO: '2026-07-23',
    category: 'Business Events',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064523804-WhatsApp Image 2026-05-11 at 15.42.14.jpg',
    link: '/blog/corporate-event-venue-in-purulia',
    cluster: 'banquet',
  },

  // ── Cluster 4: Travel Guide ───────────────────────────────────
  {
    id: 'b6',
    title: 'Places to Visit in Ajodhya Hill | Forest Reserve, Thurga Dam & Deulghata',
    excerpt: 'Explore places to visit in Ajodhya Hill near The Divine Oasis. Ajodhya Hills & Forest Reserve, Thurga Dam, Deulghata Temples, and Barabhum.',
    date: 'Oct 22, 2025',
    dateISO: '2025-10-22',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064442350-WhatsApp Image 2026-05-11 at 15.42.12 (1).jpg',
    link: '/blog/places-to-visit-in-ajodhya-hill',
    cluster: 'travel',
  },
  {
    id: 'b16',
    title: 'Things to Do in Purulia | Trekking, Dams & Forest Activities',
    excerpt: 'Looking for things to do in Purulia? Trek Ajodhya Hills, visit Thurga Dam and Deulghata, explore the organic farm, and enjoy barbeque evenings.',
    date: 'Jun 28, 2026',
    dateISO: '2026-06-28',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064432393-WhatsApp Image 2026-05-11 at 15.42.15.jpg',
    link: '/blog/things-to-do-in-purulia',
    cluster: 'travel',
  },
  {
    id: 'b17',
    title: 'Purulia Travel Guide | How to Reach, Where to Stay & What to Eat',
    excerpt: 'Complete Purulia travel guide. How to reach Purulia Junction, where to stay on Ajodhya Hill, and what to eat near the forest reserve.',
    date: 'Jun 25, 2026',
    dateISO: '2026-06-25',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064442350-WhatsApp Image 2026-05-11 at 15.42.12 (1).jpg',
    link: '/blog/purulia-travel-guide',
    cluster: 'travel',
  },
  {
    id: 'b18',
    title: 'Local Food Guide in Purulia | Bengali Bhoj, Organic Thali & More',
    excerpt: 'Explore the Purulia food scene. Local Bengali dishes, organic thali from the farm, and hilltop dining near Ajodhya at The Divine Oasis.',
    date: 'Jun 22, 2026',
    dateISO: '2026-06-22',
    dateModifiedISO: '2026-07-23',
    category: 'Food & Culture',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064507861-WhatsApp Image 2026-05-11 at 15.42.13 (1).jpg',
    link: '/blog/local-food-guide-in-purulia',
    cluster: 'travel',
  },
  {
    id: 'b19',
    title: 'Shopping in Purulia | Local Markets, Handloom & Souvenirs',
    excerpt: 'Guide to shopping in Purulia. Local markets, Baluchari and handloom textiles, terracotta crafts, and forest souvenirs near Ajodhya Hill.',
    date: 'Jun 20, 2026',
    dateISO: '2026-06-20',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/2026-05-13-064516081-WhatsApp Image 2026-05-11 at 15.42.14 (1).jpg',
    link: '/blog/shopping-in-purulia',
    cluster: 'travel',
  },
]