export interface BlogPost {
  id: string
  title: string
  excerpt: string
  date: string
  dateISO: string
  dateModifiedISO: string
  category: string
  image: string
  link: string
  cluster: 'hotel' | 'restaurant' | 'banquet' | 'travel'
}

export const blogPosts: BlogPost[] = [
  // ── Cluster 1: Hotel ──────────────────────────────────────────
  {
    id: 'b1',
    title: 'Best Hotels in Purnea Near Bus Stand | Hotel Guide 2026',
    excerpt: 'Looking for the best hotel in Purnea near Bus Stand? Compare deluxe AC rooms, budget stays, family rooms, and luxury options at Hotel Surya Bella Casa.',
    date: 'Mar 15, 2026',
    dateISO: '2026-03-15',
    dateModifiedISO: '2026-07-23',
    category: 'Hotel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3815.avif',
    link: '/blog/best-hotels-in-purnea-near-bus-stand',
    cluster: 'hotel',
  },
  {
    id: 'b4',
    title: 'Business Hotel in Purnea | Corporate Stay Near Bus Stand',
    excerpt: 'Best business hotel in Purnea near Bus Stand with conference hall, meeting room, high-speed WiFi. Ideal for corporate travelers.',
    date: 'Dec 5, 2025',
    dateISO: '2025-12-05',
    dateModifiedISO: '2026-07-23',
    category: 'Business Travel',
    image: 'https://bookonelocal.in/cdn/IMG_3703.avif',
    link: '/blog/business-hotel-in-purnea',
    cluster: 'hotel',
  },
  {
    id: 'b5',
    title: 'Family Hotel in Purnea | Safe Family Stay Near Bus Stand',
    excerpt: 'Best family hotel in Purnea near Bus Stand. Spacious family rooms, safe environment, elevator access, 24/7 staff assistance.',
    date: 'Nov 18, 2025',
    dateISO: '2025-11-18',
    dateModifiedISO: '2026-07-23',
    category: 'Family Stay',
    image: 'https://bookonelocal.in/cdn/IMG_3701.avif',
    link: '/blog/family-hotel-in-purnea',
    cluster: 'hotel',
  },
  {
    id: 'b7',
    title: 'Luxury Hotel in Purnea | Premium Stay Near Vikass Market',
    excerpt: 'Experience luxury at Hotel Surya Bella Casa in Purnea. Premium AC rooms, rooftop dining, and banquet facilities near Vikass Market.',
    date: 'Jul 20, 2026',
    dateISO: '2026-07-20',
    dateModifiedISO: '2026-07-23',
    category: 'Luxury Stay',
    image: 'https://bookonelocal.in/cdn/IMG_3808.avif',
    link: '/blog/luxury-hotel-in-purnia',
    cluster: 'hotel',
  },
  {
    id: 'b8',
    title: 'Hotels Near Purnia Railway Station | Best Stay 6 km from Junction',
    excerpt: 'Finding hotels near Purnia Railway Station? Hotel Surya Bella Casa is 6 km from Purnea Junction with free pickup, WiFi, and parking.',
    date: 'Jul 18, 2026',
    dateISO: '2026-07-18',
    dateModifiedISO: '2026-07-23',
    category: 'Hotel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3791.avif',
    link: '/blog/hotels-near-purnia-railway-station',
    cluster: 'hotel',
  },

  {
    id: 'b20',
    title: 'Best Hotel Rooms in Purnea | Comfortable Stay Near Bus Stand',
    excerpt: 'Book the best hotel rooms in Purnea at Hotel Surya Bella Casa. AC rooms, free WiFi, parking, restaurant, and family-friendly comfort near Bus Stand.',
    date: 'Jul 23, 2026',
    dateISO: '2026-07-23',
    dateModifiedISO: '2026-07-23',
    category: 'Hotel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3815.avif',
    link: '/blog/best-hotel-rooms-in-purnea',
    cluster: 'hotel',
  },

  // ── Cluster 2: Restaurant ─────────────────────────────────────
  {
    id: 'b2',
    title: 'Rooftop Restaurant in Purnea | Best Family Dining Near Bus Stand',
    excerpt: 'Discover the best rooftop restaurant in Purnea near Bus Stand. Multi cuisine dining at Hotel Surya Bella Casa — Indian, Tandoor, Mughlai, Asian & Continental.',
    date: 'Feb 20, 2026',
    dateISO: '2026-02-20',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3739.avif',
    link: '/blog/rooftop-restaurant-in-purnea',
    cluster: 'restaurant',
  },
  {
    id: 'b9',
    title: 'Best Restaurant in Purnea | Top Rated Dining Near Bus Stand',
    excerpt: 'Looking for the best restaurant in Purnea? Hotel Surya Bella Casa serves multi-cuisine food with rooftop views near Bus Stand.',
    date: 'Jul 15, 2026',
    dateISO: '2026-07-15',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3808.avif',
    link: '/blog/best-restaurant-in-purnia',
    cluster: 'restaurant',
  },
  {
    id: 'b10',
    title: 'Fine Dining Restaurant in Purnea | Elegant Multi-Cuisine Experience',
    excerpt: 'Enjoy fine dining in Purnea at Hotel Surya Bella Casa. Elegant ambiance, curated menu, rooftop views, and premium service near Bus Stand.',
    date: 'Jul 12, 2026',
    dateISO: '2026-07-12',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3784.avif',
    link: '/blog/fine-dining-restaurant-in-purnia',
    cluster: 'restaurant',
  },
  {
    id: 'b11',
    title: 'Family Restaurant in Purnea | Kid-Friendly Dining Near Bus Stand',
    excerpt: 'Find a family-friendly restaurant in Purnea. Hotel Surya Bella Casa offers pure veg and non-veg options, spacious seating, and rooftop dining.',
    date: 'Jul 10, 2026',
    dateISO: '2026-07-10',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3701.avif',
    link: '/blog/family-restaurant-in-purnia',
    cluster: 'restaurant',
  },
  {
    id: 'b12',
    title: 'Best Dinner Place in Purnea | Rooftop Evening Dining Experience',
    excerpt: 'Searching for the best dinner place in Purnea? Enjoy rooftop dinner with city views at Hotel Surya Bella Casa near Bus Stand.',
    date: 'Jul 8, 2026',
    dateISO: '2026-07-08',
    dateModifiedISO: '2026-07-23',
    category: 'Restaurant & Dining',
    image: 'https://bookonelocal.in/cdn/IMG_3766.avif',
    link: '/blog/best-dinner-place-in-purnia',
    cluster: 'restaurant',
  },

  // ── Cluster 3: Banquet & Events ───────────────────────────────
  {
    id: 'b3',
    title: 'Banquet Hall & Wedding Venue in Purnea | Marriage Hall Near Bus Stand',
    excerpt: 'Plan your wedding at the best banquet hall in Purnea near Bus Stand. Wedding venue, marriage hall, conference hall for events at Hotel Surya Bella Casa.',
    date: 'Jan 10, 2026',
    dateISO: '2026-01-10',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Weddings',
    image: 'https://bookonelocal.in/cdn/IMG_3766.avif',
    link: '/blog/banquet-hall-wedding-venue-in-purnea',
    cluster: 'banquet',
  },
  {
    id: 'b13',
    title: 'Wedding Venue in Purnea | Best Marriage Hall Near Vikass Market',
    excerpt: 'Book the best wedding venue in Purnea at Hotel Surya Bella Casa. Elegant banquet hall, catering, decor, and room blocks for guests near Vikass Market.',
    date: 'Jul 5, 2026',
    dateISO: '2026-07-05',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Weddings',
    image: 'https://bookonelocal.in/cdn/IMG_3764.avif',
    link: '/blog/wedding-venue-in-purnia',
    cluster: 'banquet',
  },
  {
    id: 'b14',
    title: 'Birthday Party Venue in Purnea | Celebration Hall Near Bus Stand',
    excerpt: 'Celebrate your birthday at Hotel Surya Bella Casa in Purnea. Banquet hall, rooftop dining, decoration packages, and group booking near Bus Stand.',
    date: 'Jul 3, 2026',
    dateISO: '2026-07-03',
    dateModifiedISO: '2026-07-23',
    category: 'Events & Parties',
    image: 'https://bookonelocal.in/cdn/IMG_3709.jpeg',
    link: '/blog/birthday-party-venue-in-purnia',
    cluster: 'banquet',
  },
  {
    id: 'b15',
    title: 'Corporate Event Venue in Purnea | Conference & Meeting Hall',
    excerpt: 'Host corporate events in Purnea at Hotel Surya Bella Casa. Conference hall, AV equipment, catering, and team outing packages near Bus Stand.',
    date: 'Jul 1, 2026',
    dateISO: '2026-07-01',
    dateModifiedISO: '2026-07-23',
    category: 'Business Events',
    image: 'https://bookonelocal.in/cdn/IMG_3703.avif',
    link: '/blog/corporate-event-venue-in-purnia',
    cluster: 'banquet',
  },

  // ── Cluster 4: Travel Guide ───────────────────────────────────
  {
    id: 'b6',
    title: 'Places to Visit in Purnea | Nearby Attractions & Things to Do',
    excerpt: 'Explore places to visit in Purnea near Hotel Surya Bella Casa. Puran Devi Temple, Kali Mandir, shopping markets, and local attractions.',
    date: 'Oct 22, 2025',
    dateISO: '2025-10-22',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: '/purneacity.jpg',
    link: '/blog/places-to-visit-in-purnea',
    cluster: 'travel',
  },
  {
    id: 'b16',
    title: 'Things to Do in Purnea | Weekend Activities & Experiences',
    excerpt: 'Looking for things to do in Purnea? Explore temples, markets, food streets, and day trips from Hotel Surya Bella Casa near Bus Stand.',
    date: 'Jun 28, 2026',
    dateISO: '2026-06-28',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3809.avif',
    link: '/blog/things-to-do-in-purnia',
    cluster: 'travel',
  },
  {
    id: 'b17',
    title: 'Purnia Travel Guide | How to Reach, Where to Stay & What to Eat',
    excerpt: 'Complete Purnia travel guide. How to reach by train, bus, and flight. Best areas to stay, food to try, and top attractions near Hotel Surya Bella Casa.',
    date: 'Jun 25, 2026',
    dateISO: '2026-06-25',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3815.avif',
    link: '/blog/purnia-travel-guide',
    cluster: 'travel',
  },
  {
    id: 'b18',
    title: 'Local Food Guide in Purnea | Must-Try Dishes & Best Restaurants',
    excerpt: 'Explore Purnea food scene. Litti Chokha, Thekua, Mitha Khana, and local Bihari cuisine. Best restaurants and street food near Hotel Surya Bella Casa.',
    date: 'Jun 22, 2026',
    dateISO: '2026-06-22',
    dateModifiedISO: '2026-07-23',
    category: 'Food & Culture',
    image: 'https://bookonelocal.in/cdn/IMG_3739.avif',
    link: '/blog/local-food-guide-in-purnia',
    cluster: 'travel',
  },
  {
    id: 'b19',
    title: 'Shopping in Purnea | Best Markets, Malls & Local Bazaars',
    excerpt: 'Guide to shopping in Purnea. Vikass Market, Bhatta Bazar, City Mall, and local bazaars for fabrics, electronics, and street shopping near Hotel Surya Bella Casa.',
    date: 'Jun 20, 2026',
    dateISO: '2026-06-20',
    dateModifiedISO: '2026-07-23',
    category: 'Travel Guide',
    image: 'https://bookonelocal.in/cdn/IMG_3809.avif',
    link: '/blog/shopping-in-purnia',
    cluster: 'travel',
  },
]
